Added README.md
tensorflow/models pull request #10259
Opened 2021-09-15 15:39 UTC by ykate1998

Added README for global features model

2021-09-15 20:04 UTC, andrefaraujo requested changes
Thanks Kate, this looks great. I found one small nit, see comment.

Another comment I had is: once the model is trained, how can we export the model to evaluate in a different dataset? Eg, something like this for DELG: https://github.com/tensorflow/models/tree/master/research/delf/delf/python/training#exporting-the-trained-model

2021-10-19 21:36 UTC, andrefaraujo commented
@ykate1998 friendly ping :)

2021-11-14 06:43 UTC, ykate1998 commented on research/delf/delf/python/training/model/export_CNN_global.py
> +    return self._model(exp_image, training=False)
Thank you for pointing this out

2021-11-16 23:32 UTC, andrefaraujo approved these changes
Looks perfect, thanks!

2021-11-16 23:32 UTC, merged