Documentation Data Efficient Transformer
tensorflow/models pull request #10458
Opened 2022-01-13 19:01 UTC by sigeisler

# Description

> :memo: Please include a summary of the change. 
>  
> * Please also include relevant motivation and context.  
> * List any dependencies that are required for this change.  

## Type of change

For a new feature or function, please create an issue first to discuss it
with us before submitting a pull request.

Note: Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation update
- [ ] TensorFlow 2 migration
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] A new research paper code implementation
- [x] Other (Specify): jupyter/colab notebook showing the effect of the augmentations

## Tests

> :memo: Please describe the tests that you ran to verify your changes.
>  
> * Provide instructions so we can reproduce.  
> * Please also list any relevant details for your test configuration.  

**Test Configuration**:

## Checklist

- [x] I have signed the [Contributor License Agreement](https://github.com/tensorflow/models/wiki/Contributor-License-Agreements).
- [x] I have read [guidelines for pull request](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).
- [x] My code follows the [coding guidelines](https://github.com/tensorflow/models/wiki/Coding-guidelines).
- [x] I have performed a self [code review](https://github.com/tensorflow/models/wiki/Code-review) of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.

2022-01-13 19:56 UTC, xianzhidu approved these changes

2022-01-13 23:11 UTC, jaeyounkim approved these changes

2022-01-13 23:15 UTC, xianzhidu approved these changes

2022-04-06 05:03 UTC, saberkun commented
Hi, this PR is failed to merge. The vit project is moved to projects/vit. Could you help update the PR? Thank you.

2022-07-29 20:38 UTC, sigeisler commented
@saberkun what exactly do you ned me to do?

2022-07-30 00:46 UTC, akaye47 commented
Why do Git Hub folks always ask me things I don’t understand?On Fri, Jul 29, 2022 at 4:41 PM Simon Geisler ***@***.***> wrote:
@saberkun what exactly do you ned me to do?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2022-07-30 22:53 UTC, saberkun requested changes
The Vit project folder has been moved: https://github.com/tensorflow/models/tree/master/official/projects/vit

2023-02-10 21:16 UTC, fyangf reviewed
The entire folder `vit` is removed and all related code has been moved under https://github.com/tensorflow/models/tree/master/official/vision/modeling/backbones, so we may consider closing if it is not updated. The original POC left so we do not have the full context now.

2023-04-06 17:06 UTC, closed without merging