Update Open CV installation step in Fine-tuning BERT tutorial
tensorflow/models pull request #10766
Opened 2022-09-06 22:30 UTC by 8bitmp3

@MarkDaoust @markmcd 

Currently, importing TF Models throws an `ImportError` as there's no `cv2` dependency. This PR should fix this step with `pip install opencv-python`.

2022-09-12 22:11 UTC, 8bitmp3 commented
@MarkDaoust The other docs that use OpenCV have a separate issue unrelated to OpenCV. Please review this PR, thanks!

2022-09-14 16:48 UTC, MarkDaoust requested changes
Could you also get:

models/docs/vision/image_classification.ipynb

2022-09-14 17:18 UTC, saberkun approved these changes

2022-09-14 19:21 UTC, 8bitmp3 commented
@MarkDaoust @saberkun 

> Could you also get:
>
> models/docs/vision/image_classification.ipynb

👍 In a separate PR after some debugging

2022-09-20 20:23 UTC, 8bitmp3 commented
@MarkDaoust @saberkun

> > Could you also get:
> >
> > models/docs/vision/image_classification.ipynb
>
> 👍 In a separate PR after some debugging

image_classification.ipynb needs to be fixed separately. After running:

```python
with distribution_strategy.scope():
  model_dir = tempfile.mkdtemp()
  task = tfm.core.task_factory.get_task(exp_config.task, logging_dir=model_dir)

tf.keras.utils.plot_model(task.build_model(), show_shapes=True)
```

You'd get the following in Colab:

```
InvocationException: Program terminated with status: 1. stderr follows: Error: bad label format {res_net|ResNet}|{input:|output:}|{{(None, 32, 32, 3)}|{/{'2': (None, 8, 8, 64), '3': (None, 4, 4, 128), '4': (None, 2, 2, 256), '5': (None, 1, 1, 512)/}}}
```

2022-09-22 02:41 UTC, saberkun commented
I think we can leave models/docs/vision/image_classification.ipynb and first merge this PR.

2022-09-22 02:41 UTC, saberkun approved these changes

2022-09-23 04:57 UTC, merged