loading a2 rather than a0
tensorflow/models pull request #11187
Opened 2024-04-04 18:50 UTC by MustafaLotfi

In the documentation that is provided for MoViNet tutorial, it says we will download MoViNet-A0-Stream. But In the code MoViNet-A2 is downloaded and used.

2024-04-04 19:03 UTC, laxmareddyp commented
Hi @Chen-Zhe @chaoyan1037 ,

PR having typo changes , Please approve in your free time.Thanks

2024-09-16 07:53 UTC, LakshmiKalaKadali commented
Hi @Chen-Zhe, @chaoyan1037,

Could you please review the PR.

Thank You

2024-09-25 16:33 UTC, chaoyan1037 requested changes
Instead of change comments, maybe update "load_movinet_from_hub('a2', 'stream', hub_version=3)" to be "load_movinet_from_hub('a0', 'stream', hub_version=3)" since the following section Export a Streaming Model to TensorFlow Lite for Mobile also use 'a0' as example.

2024-09-26 12:14 UTC, MustafaLotfi commented
@chaoyan1037 
In the previous cells, MoViNet-A2-base is loaded and used, Wouldn't it be a better approach to use a same version (A2) for stream model too?

2024-10-19 18:42 UTC, chaoyan1037 commented
I see.

2024-10-19 18:43 UTC, chaoyan1037 approved these changes

2024-10-23 18:06 UTC, merged