Global model
tensorflow/models pull request #9902
Opened 2021-04-13 19:40 UTC by ykate1998

# Description

Adding the CNN Image Retrieval model implementation based on the following papers:

[1] Fine-tuning CNN Image Retrieval with No Human Annotation,
Radenović F., Tolias G., Chum O., TPAMI 2018 [arXiv]
https://arxiv.org/abs/1711.02512

[2] CNN Image Retrieval Learns from BoW: Unsupervised Fine-Tuning with Hard
Examples, Radenović F., Tolias G., Chum O., ECCV 2016 [arXiv]
https://arxiv.org/abs/1604.02426

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] A new research paper code implementation

2021-05-18 01:04 UTC, andrefaraujo requested changes
Thanks, Kate! It looks good overall, the comments I have are generally minor. Please take a look :)

2021-05-18 01:04 UTC, andrefaraujo commented on research/delf/delf/python/training/model/global_model.py
> +def extract_ms(net, input, ms, msp):
maybe rename to extract_multi_scale_descriptor

2021-05-18 01:04 UTC, andrefaraujo commented on research/delf/delf/python/training/model/global_model.py
> +    msp: Float, multi-scale normalization power parameter.
same terminology comment as in the previous function

2021-05-18 01:04 UTC, andrefaraujo commented on research/delf/delf/python/training/model/global_model_test.py
> +  def testExtractMS(self):
testExtractMultiScale

2021-06-18 15:08 UTC, ykate1998 commented on research/delf/delf/python/training/model/global_model.py
> +      net_in.add(tf.keras.layers.ReLU())
As far as I can tell, all models are imported in keras.Model format, not only EfficientNet. The code you pointed out seems to be working in the case of DenseNet

2021-06-18 23:55 UTC, ykate1998 commented on research/delf/delf/python/training/model/global_model.py
> +      net_in.add(tf.keras.layers.ReLU())
Sorry, you were right, I tested this specific pass and it needs the conversion to Sequential as you mentioned

2021-06-19 01:12 UTC, ykate1998 commented
@andrefaraujo , I believe it should be fixed now. Thank you for the review

2021-07-06 18:43 UTC, andrefaraujo requested changes
Thanks Kate! Looks great. Just one small change left, and I will merge the code once you make the edit.

2021-07-06 18:43 UTC, andrefaraujo commented on research/delf/delf/python/training/model/global_model.py
> +      net_in.add(tf.keras.layers.ReLU())
Thanks!

2021-07-06 18:43 UTC, andrefaraujo commented on research/delf/delf/python/training/model/global_model_test.py
> +            multi_scale_power=2, print_freq=1)
fix indentation here (pull code to previous line)

2021-07-07 09:57 UTC, ykate1998 commented
@andrefaraujo, should be fixed now :) Thank you

2021-07-07 18:28 UTC, andrefaraujo approved these changes
Thanks, Kate!

2021-07-07 18:30 UTC, andrefaraujo commented
@ykate1998 can you please resolve the conflict? I cannot merge it right now. Once you resolve the conflict, I'll be able to merge. I guess it may be related to the other PR which I just merged.

2021-07-09 07:59 UTC, ykate1998 commented
Hello, should be fixed now. Thanks

2021-07-13 17:02 UTC, andrefaraujo approved these changes
Thanks Kate! Merging...

2021-07-13 17:02 UTC, merged